version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: jwt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jwt-db
    ports:
      - '5433:5432'